### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [jmgirard/circumplex#14]
Hi

We are planning a new release of ggplot2 and our tests show issues with circumplex. Specifically you are re-exporting ggsave but the signature of ggsave is changed slightly in the new version which means that your docs no longer matches it, resulting in a check warning for your package

https://github.com/jmgirard/circumplex/blob/6b11f608d0f7afc9ceef61dca34e281d3f011a15/R/utils.R#L13-L25

We plan to submit the next version of ggplot2 on May 31st

best
Thomas

**Comment by jmgirard** [comment]
Should be addressed by https://github.com/jmgirard/circumplex/commit/f867b30772130f07f036c57e11337575ed62a84a
